LineLength:
  Max: 120
  Exclude:
    - "**/attributes/*.rb"
    - "**/metadata.rb"

HashSyntax:
  Exclude:
    - "**/Berksfile"

EmptyLines:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Exclude:
  - metadata.rb
